### ISSUE TITLE
Asking help about the XRoad?

### ISSUE THREAD

**Issue by darapenhchet** [ria-ee/X-Road-EE-docs#15]
Dear XRoad,

May I ask you about the Central Monitoring Server what package should we install?

![image](https://user-images.githubusercontent.com/8038324/75089727-86974900-558e-11ea-97a9-ba4758a4f605.png)

Best Regards,
Dara Penhchet

**Comment by VitaliStupin** [comment]
This repository contains Estonia specific documentation for X-Road and does not provide support for X-Road software.

Please join X-Road Slack if you have questions: https://x-road.global/join-the-xroad-community

Or if you have found bugs report them to the correct repository: https://github.com/nordic-institute/X-Road/issues
