### ISSUE TITLE
I have a error when I intall the Xroad Unit xroad-confclient.service not found.

### ISSUE THREAD

**Issue by Oscarloac** [ria-ee/X-Road-EE-docs#9]
Hi all,

Excuse me someone can help me, I'm installing the Xroad Security Server but I have the following problem:

dt_bi@FORTLAB:/u01/X-Road-develop/src$ sudo apt-get install xroad-securityserver
[sudo] password for dt_bi:
Reading package lists... Done
Building dependency tree
Reading state information... Done
xroad-securityserver is already the newest version (6.19.0-1).
xroad-securityserver set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
7 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up xroad-proxy (6.19.0-1) ...
running serverconf database migrations
Liquibase Home is not set.
Liquibase Update Successful
Configuring groups
The user `dt_bi' is already a member of `xroad-security-officer'.
The user `dt_bi' is already a member of `xroad-registration-officer'.
The user `dt_bi' is already a member of `xroad-service-administrator'.
The user `dt_bi' is already a member of `xroad-system-administrator'.
The user `dt_bi' is already a member of `xroad-securityserver-observer'.
Failed to restart xroad-confclient.service: Unit xroad-confclient.service not found.
dpkg: error processing package xroad-proxy (--configure):
 subprocess installed post-installation script returned error exit status 5
dpkg: dependency problems prevent configuration of xroad-addon-messagelog:
 xroad-addon-messagelog depends on xroad-proxy (= 6.19.0-1); however:
  Package xroad-proxy is not configured yet.

dpkg: error processing package xroad-addon-messagelog (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          No apport report written because the error message indicates its a followup error from a previous failure.
                                                                             dpkg: dependency problems prevent configuration of xroad-addon-metaservices:
 xroad-addon-metaservices depends on xroad-proxy (= 6.19.0-1); however:
  Package xroad-proxy is not configured yet.

dpkg: error processing package xroad-addon-metaservices (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of xroad-addon-proxymonitor:
 xroad-addon-proxymonitor depends on xroad-proxy (= 6.19.0-1); however:
  Package xroad-proxy is not configured yet.

dpkg: error processing package xroad-addon-proxymonitor (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of xroad-addon-wsdlvalidator:
 xroad-addon-wsdlvalidator depends on xroad-proxy (= 6.19.0-1); however:
  Package xroad-proxy is not configured yet.

dpkg: error processing package xroad-addon-wsdlvalidator (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached alreadyityserver:
                                                              No apport report written because MaxReports is reached already
                                                                                                                            No apport report written because MaxReports is reached already
                                                   No apport report written because MaxReports is reached already

                                                                                                                  xroad-securityserver depends on xroad-proxy (= 6.19.0-1); however:
  Package xroad-proxy is not configured yet.
 xroad-securityserver depends on xroad-addon-metaservices (= 6.19.0-1); however:
  Package xroad-addon-metaservices is not configured yet.
 xroad-securityserver depends on xroad-addon-messagelog (= 6.19.0-1); however:
  Package xroad-addon-messagelog is not configured yet.
 xroad-securityserver depends on xroad-addon-proxymonitor (= 6.19.0-1); however:
  Package xroad-addon-proxymonitor is not configured yet.
 xroad-securityserver depends on xroad-addon-wsdlvalidator (= 6.19.0-1); however:
  Package xroad-addon-wsdlvalidator is not configured yet.

dpkg: error processing package xroad-securityserver (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of xroad-securityserver-fi:
 xroad-securityserver-fi depends on xroad-securityserver (= 6.19.0-1); however:
  Package xroad-securityserver is not configured yet.

dpkg: error processing package xroad-securityserver-fi (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 xroad-proxy
 xroad-addon-messagelog
 xroad-addon-metaservices
 xroad-addon-proxymonitor
 xroad-addon-wsdlvalidator
 xroad-securityserver
 xroad-securityserver-fi
E: Sub-process /usr/bin/dpkg returned an error code (1)
dt_bi@FORTLAB:/u01/X-Road-develop/src$

This problem is very important resolv becase I have a week with this situation, please helpme.

Thanks so much.

**Comment by VitaliStupin** [comment]
Hi! I see that you have `xroad-securityserver-fi` package installed. If you are trying to install Security Server for Suomi.fi-palveluväylä then you should contact [VRK](https://www.vrk.fi). And if you are not member of Finnish environment then you should report bugs to the official X-Road repository: https://github.com/nordic-institute/X-Road/issues

**Comment by Oscarloac** [comment]
Hi VitaliStupin,

I don't have any preference for install  x-road securitysever-ee or x-road securityserver, booth send the same error, I have another question in the country México, do you know if anysome to done any instalation the X-road?

Please help me to know if I am not doing something wrong or if I am omitting some step of the installation, since it always fails to install the pakete of x-road proxy.

Thank you very much for your help.

dt_bi@FORTLAB:/u01/X-Road-develop/src$ sudo apt-get install xroad-securityserver
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  authbind crudini postgresql python-iniparse rlwrap xroad-addon-messagelog
  xroad-addon-metaservices xroad-addon-proxymonitor xroad-addon-wsdlvalidator
  xroad-base xroad-common xroad-confclient xroad-jetty9 xroad-monitor
  xroad-nginx xroad-proxy xroad-signer
Suggested packages:
  postgresql-doc
The following NEW packages will be installed:
  authbind crudini postgresql python-iniparse rlwrap xroad-addon-messagelog
  xroad-addon-metaservices xroad-addon-proxymonitor xroad-addon-wsdlvalidator
  xroad-base xroad-common xroad-confclient xroad-jetty9 xroad-monitor
  xroad-nginx xroad-proxy xroad-securityserver xroad-signer
0 upgraded, 18 newly installed, 0 to remove and 2 not upgraded.
Need to get 336 MB of archives.
After this operation, 367 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://mx.archive.ubuntu.com/ubuntu xenial/universe amd64 rlwrap amd64 0.41-1build1 [74.9 kB]
Get:2 http://mx.archive.ubuntu.com/ubuntu xenial/universe amd64 python-iniparse all 0.4-2.2 [19.6 kB]
Get:3 http://mx.archive.ubuntu.com/ubuntu xenial/universe amd64 crudini amd64 0.7-1 [12.4 kB]
Get:4 http://mx.archive.ubuntu.com/ubuntu xenial-updates/main amd64 postgresql all 9.5+173ubuntu0.2 [5,450 B]
Get:5 http://mx.archive.ubuntu.com/ubuntu xenial/main amd64 authbind amd64 2.1.1+nmu1 [17.6 kB]
Get:6 https://artifactory.niis.org/xroad-release-deb trusty-current/main amd64 xroad-base amd64 6.19.0-1 [2,786 kB]
Get:7 https://artifactory.niis.org/xroad-release-deb trusty-current/main amd64 xroad-confclient amd64 6.19.0-1 [37.7 MB]
Get:8 https://artifactory.niis.org/xroad-release-deb trusty-current/main amd64 xroad-nginx amd64 6.19.0-1 [12.1 kB]
Get:9 https://artifactory.niis.org/xroad-release-deb trusty-current/main amd64 xroad-signer amd64 6.19.0-1 [75.8 MB]
Get:10 https://artifactory.niis.org/xroad-release-deb trusty-current/main amd64 xroad-common amd64 6.19.0-1 [10.2 kB]
Get:11 https://artifactory.niis.org/xroad-release-deb trusty-current/main amd64 xroad-jetty9 all 6.19.0-1 [8,967 kB]
Get:12 https://artifactory.niis.org/xroad-release-deb trusty-current/main amd64 xroad-proxy all 6.19.0-1 [123 MB]
Err:12 http://www.nic.funet.fi/pub/csc/x-road/client/ubuntu-dev-current/packages trusty-current/main amd64 xroad-proxy all 6.19.0-1
  transfer closed with 105525215 bytes remaining to read
Get:12 http://www.nic.funet.fi/pub/csc/x-road/client/ubuntu-dev-current/packages trusty-current/main amd64 xroad-proxy all 6.19.0-1 [123 MB]
Get:13 https://artifactory.niis.org/xroad-release-deb trusty-current/main amd64 xroad-addon-messagelog all 6.19.0-1 [37.9 MB]
Get:14 https://artifactory.niis.org/xroad-release-deb trusty-current/main amd64 xroad-addon-metaservices all 6.19.0-1 [157 kB]
Get:15 https://artifactory.niis.org/xroad-release-deb trusty-current/main amd64 xroad-monitor all 6.19.0-1 [47.2 MB]
Get:16 https://artifactory.niis.org/xroad-release-deb trusty-current/main amd64 xroad-addon-proxymonitor all 6.19.0-1 [64.8 kB]
Get:17 https://artifactory.niis.org/xroad-release-deb trusty-current/main amd64 xroad-addon-wsdlvalidator all 6.19.0-1 [2,698 kB]
Get:18 https://artifactory.niis.org/xroad-release-deb trusty-current/main amd64 xroad-securityserver all 6.19.0-1 [10.1 kB]
Fetched 336 MB in 13min 9s (426 kB/s)                                          
Preconfiguring packages ...
Selecting previously unselected package rlwrap.
(Reading database ... 230442 files and directories currently installed.)
Preparing to unpack .../rlwrap_0.41-1build1_amd64.deb ...
Unpacking rlwrap (0.41-1build1) ...
Selecting previously unselected package python-iniparse.
Preparing to unpack .../python-iniparse_0.4-2.2_all.deb ...
Unpacking python-iniparse (0.4-2.2) ...
Selecting previously unselected package crudini.
Preparing to unpack .../crudini_0.7-1_amd64.deb ...
Unpacking crudini (0.7-1) ...
Selecting previously unselected package xroad-base.
Preparing to unpack .../xroad-base_6.19.0-1_amd64.deb ...
system locale set to UTF-8 compatible.
Unpacking xroad-base (6.19.0-1) ...
Selecting previously unselected package postgresql.
Preparing to unpack .../postgresql_9.5+173ubuntu0.2_all.deb ...
Unpacking postgresql (9.5+173ubuntu0.2) ...
Selecting previously unselected package xroad-confclient.
Preparing to unpack .../xroad-confclient_6.19.0-1_amd64.deb ...
Unpacking xroad-confclient (6.19.0-1) ...
Selecting previously unselected package xroad-nginx.
Preparing to unpack .../xroad-nginx_6.19.0-1_amd64.deb ...
Unpacking xroad-nginx (6.19.0-1) ...
Selecting previously unselected package xroad-signer.
Preparing to unpack .../xroad-signer_6.19.0-1_amd64.deb ...
Unpacking xroad-signer (6.19.0-1) ...
Selecting previously unselected package xroad-common.
Preparing to unpack .../xroad-common_6.19.0-1_amd64.deb ...
Unpacking xroad-common (6.19.0-1) ...
Selecting previously unselected package xroad-jetty9.
Preparing to unpack .../xroad-jetty9_6.19.0-1_all.deb ...
Unpacking xroad-jetty9 (6.19.0-1) ...
Selecting previously unselected package authbind.
Preparing to unpack .../authbind_2.1.1+nmu1_amd64.deb ...
Unpacking authbind (2.1.1+nmu1) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for doc-base (0.10.7) ...
Processing 1 added doc-base file...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up postgresql (9.5+173ubuntu0.2) ...
Setting up rlwrap (0.41-1build1) ...
update-alternatives: using /usr/bin/rlwrap to provide /usr/bin/readline-editor (readline-editor) in auto mode
Setting up python-iniparse (0.4-2.2) ...
Setting up crudini (0.7-1) ...
Setting up xroad-base (6.19.0-1) ...
The user `xroad' is already a member of `shadow'.
Setting up xroad-confclient (6.19.0-1) ...
Setting up xroad-nginx (6.19.0-1) ...
Setting up xroad-signer (6.19.0-1) ...
Processing triggers for xroad-base (6.19.0-1) ...
Setting up xroad-common (6.19.0-1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Selecting previously unselected package xroad-proxy.
(Reading database ... 230939 files and directories currently installed.)
Preparing to unpack .../xroad-proxy_6.19.0-1_all.deb ...
Generating new nginx.[crt|key] files 
generating new webUI TLS key/certificate with /CN=FORTLAB and IP:172.19.205.30,IP:172.17.0.1,DNS:FORTLAB,DNS:FORTLAB
/CN=FORTLAB -subj
Generating new internal.[crt|key|p12] files 
generating new service TLS key/certificate with /CN=FORTLAB and IP:172.19.205.30,IP:172.17.0.1,DNS:FORTLAB,DNS:FORTLAB
/CN=FORTLAB -subj
Unpacking xroad-proxy (6.19.0-1) ...
Selecting previously unselected package xroad-addon-messagelog.
Preparing to unpack .../xroad-addon-messagelog_6.19.0-1_all.deb ...
Unpacking xroad-addon-messagelog (6.19.0-1) ...
Selecting previously unselected package xroad-addon-metaservices.
Preparing to unpack .../xroad-addon-metaservices_6.19.0-1_all.deb ...
Unpacking xroad-addon-metaservices (6.19.0-1) ...
Selecting previously unselected package xroad-monitor.
Preparing to unpack .../xroad-monitor_6.19.0-1_all.deb ...
Unpacking xroad-monitor (6.19.0-1) ...
Selecting previously unselected package xroad-addon-proxymonitor.
Preparing to unpack .../xroad-addon-proxymonitor_6.19.0-1_all.deb ...
Unpacking xroad-addon-proxymonitor (6.19.0-1) ...
Selecting previously unselected package xroad-addon-wsdlvalidator.
Preparing to unpack .../xroad-addon-wsdlvalidator_6.19.0-1_all.deb ...
Unpacking xroad-addon-wsdlvalidator (6.19.0-1) ...
Selecting previously unselected package xroad-securityserver.
Preparing to unpack .../xroad-securityserver_6.19.0-1_all.deb ...
Unpacking xroad-securityserver (6.19.0-1) ...
Processing triggers for xroad-base (6.19.0-1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up xroad-jetty9 (6.19.0-1) ...
Setting up authbind (2.1.1+nmu1) ...
Setting up xroad-monitor (6.19.0-1) ...
Processing triggers for xroad-base (6.19.0-1) ...
Setting up xroad-proxy (6.19.0-1) ...
no db settings detected, creating local db
CREATE ROLE
CREATE EXTENSION
running serverconf database migrations
Liquibase Home is not set.
Liquibase Update Successful
Configuring groups
The user `dt_bi' is already a member of `xroad-security-officer'.
The user `dt_bi' is already a member of `xroad-registration-officer'.
The user `dt_bi' is already a member of `xroad-service-administrator'.
The user `dt_bi' is already a member of `xroad-system-administrator'.
The user `dt_bi' is already a member of `xroad-securityserver-observer'.
Failed to restart xroad-confclient.service: Unit xroad-confclient.service not found.
dpkg: error processing package xroad-proxy (--configure):
 subprocess installed post-installation script returned error exit status 5
dpkg: dependency problems prevent configuration of xroad-addon-messagelog:
 xroad-addon-messagelog depends on xroad-proxy (= 6.19.0-1); however:
  Package xroad-proxy is not configured yet.

dpkg: error processing package xroad-addon-messagelog (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of xroad-addon-metaservices:
 xroad-addon-metaservices depends on xroad-proxy (= 6.19.0-1); however:
  Package xroad-proxy is not configured yet.

dpkg: error processing package xroad-addon-metaservices (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of xroad-addon-proxymonitor:
 xroad-addon-proxymonitor depends on xroad-proxy (= 6.19.0-1); however:
  Package xroad-proxy is not configured yet.

dpkg: error processing package xroad-addon-proxymonitor (--confNo apport report written because the error message indicates its a followup error from a previous failure.
         No apport report written because the error message indicates its a followup error from a previous failure.
                                   No apport report written because MaxReports is reached already
                 No apport report written because MaxReports is reached already
                                                                               igure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of xroad-addon-wsdlvalidator:
 xroad-addon-wsdlvalidator depends on xroad-proxy (= 6.19.0-1); however:
  Package xroad-proxy is not configured yet.

dpkg: error processing package xroad-addon-wsdlvalidator (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of xroad-securityserver:
 xroad-securityserver depends on xroad-proxy (= 6.19.0-1); however:
  Package xroad-proxy is not configured yet.
 xroad-securityserver depends on xroad-addon-metaservices (= 6.19.0-1); however:
  Package xroad-addon-metaservices is not configured yet.
 xroad-securityserver depends on xroad-addon-messagelog (= 6.19.0-1); however:
  Package xroad-addon-messagelog is not configured yet.
 xroad-securityserver depends on xroad-addon-proxymonitor (= 6.19.0-1); however:
  Package xroad-addon-proxymonitor is not configured yet.
 xroad-securityserver depends on xroad-addon-wsdlvalidator (= 6.19.0-1); however:
  Package xroad-addon-wsdlvalidator is not configured yet.

dpkg: error processing package xroad-securityserver (--configure):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-19) ...No apport report written because MaxReports is reached already

Processing triggers for xroad-base (6.19.0-1) ...
Errors were encountered while processing:
 xroad-proxy
 xroad-addon-messagelog
 xroad-addon-metaservices
 xroad-addon-proxymonitor
 xroad-addon-wsdlvalidator
 xroad-securityserver
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by VitaliStupin** [comment]
You are probably installing packages for Ubuntu 14.04 on a Ubuntu 16.04 machine. That is not supported.

**Comment by Oscarloac** [comment]
Hi Vitali, 

Thanks for your help, I changed the Operation Sistem Ubuntu 16.04 for Ubuntu 14.04 and the installation finish successful. 

Thank you so much.
